import Foundation
import Combine
import os

/// Parses Claude Code's streaming JSON output (one JSON object per line) into structured LogEntry values.
///
/// Claude Code with `--output-format stream-json` outputs newline-delimited JSON objects.
/// Each object has a `type` field indicating the message type:
/// - `assistant`: text content from Claude, OR tool_use invocations wrapped in message.content[]
/// - `user`: tool results returned to Claude (message.content[] with tool_result blocks)
/// - `tool_use`: a tool invocation (flat format)
/// - `tool_result`: the result of a tool invocation (flat format)
/// - `result`: the final result of the session
/// - `system`: system messages, including `subtype: "init"` for session initialization
/// - Other types are treated as system messages
///
/// Supports both flat format (`{"type":"assistant","content":"text"}`) and
/// nested format where content lives inside a `message` dict (`{"type":"assistant","message":{"content":[...]}}`).
final class StreamingJSONParser {
    private static let logger = Logger(subsystem: "com.amattn.Ridler", category: "StreamingJSONParser")

    private let entrySubject = PassthroughSubject<LogEntry, Never>()
    private let completionSubject = PassthroughSubject<Void, Never>()

    /// Publisher that emits parsed log entries.
    var entryPublisher: AnyPublisher<LogEntry, Never> {
        entrySubject.eraseToAnyPublisher()
    }

    /// Publisher that emits when the ridler-complete signal is detected.
    var completionPublisher: AnyPublisher<Void, Never> {
        completionSubject.eraseToAnyPublisher()
    }

    /// Parse a single line of streaming JSON output from Claude Code.
    /// Returns the parsed LogEntry, or nil if the line could not be parsed.
    @discardableResult
    func parseLine(_ line: String) -> LogEntry? {
        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty else { return nil }

        // Check for ridler-complete signal in raw text
        if trimmed.contains("<ridler-complete/>") {
            completionSubject.send()
        }

        guard let data = trimmed.data(using: .utf8) else {
            Self.logger.warning("StreamingJSONParser: Could not convert line to UTF-8 data")
            return nil
        }

        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            Self.logger.warning("StreamingJSONParser: Malformed JSON line: \(trimmed.prefix(200))")
            return nil
        }

        let entry = parseJSON(json, rawJSON: trimmed)

        // Also check for ridler-complete signal in parsed content
        if entry.content.contains("<ridler-complete/>") {
            completionSubject.send()
        }

        entrySubject.send(entry)
        return entry
    }

    /// Subscribe to a line publisher (e.g., from ClaudeCodeProcessManager) and parse each line.
    /// Returns a cancellable subscription.
    func subscribe(to linePublisher: AnyPublisher<String, Never>) -> AnyCancellable {
        linePublisher
            .sink { [weak self] line in
                self?.parseLine(line)
            }
    }

    // MARK: - Static Loading

    /// Parse a single line from ridler.log, extracting ridler_* metadata fields.
    /// Returns the parsed LogEntry and the extracted storyID, or nil if the line cannot be parsed.
    static func parseLineForLoad(_ line: String) -> (entry: LogEntry, storyID: String?)? {
        let trimmed = line.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmed.isEmpty,
              let data = trimmed.data(using: .utf8),
              var json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            return nil
        }

        // Extract ridler metadata — require ridler_timestamp to distinguish
        // new NDJSON format from old raw-stdout log lines
        let storyID = json.removeValue(forKey: "ridler_story_id") as? String
        let timestampStr = json.removeValue(forKey: "ridler_timestamp") as? String
        let ridlerType = json.removeValue(forKey: "ridler_type") as? String

        guard let timestampStr else { return nil }

        let formatter = ISO8601DateFormatter()
        formatter.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        let timestamp = formatter.date(from: timestampStr) ?? Date()

        // Handle system entries generated by Ridler itself
        if ridlerType == "system" {
            let content = json["content"] as? String ?? ""
            return (
                entry: LogEntry(timestamp: timestamp, type: .system, content: content, storyID: storyID),
                storyID: storyID
            )
        }

        // Re-serialize the cleaned JSON (without ridler_ fields) for rawJSON
        let cleanedJSON: String
        if let cleanedData = try? JSONSerialization.data(withJSONObject: json, options: []),
           let str = String(data: cleanedData, encoding: .utf8) {
            cleanedJSON = str
        } else {
            cleanedJSON = trimmed
        }

        // Parse as a Claude Code entry
        let parser = StreamingJSONParser()
        let entry = parser.parseJSONDirect(json, rawJSON: cleanedJSON)
        return (
            entry: LogEntry(
                timestamp: timestamp,
                type: entry.type,
                content: entry.content,
                storyID: storyID,
                rawJSON: cleanedJSON
            ),
            storyID: storyID
        )
    }

    // MARK: - Internal

    /// Parse a JSON dict into a LogEntry without publishing to subjects.
    func parseJSONDirect(_ json: [String: Any], rawJSON: String) -> LogEntry {
        parseJSON(json, rawJSON: rawJSON)
    }

    // MARK: - Private

    private func parseJSON(_ json: [String: Any], rawJSON: String) -> LogEntry {
        let type = json["type"] as? String ?? ""

        switch type {
        case "assistant":
            return parseAssistantMessage(json, rawJSON: rawJSON)
        case "user":
            return parseUserMessage(json, rawJSON: rawJSON)
        case "tool_use":
            return parseToolUse(json, rawJSON: rawJSON)
        case "tool_result":
            return parseToolResult(json, rawJSON: rawJSON)
        case "result":
            return parseResult(json, rawJSON: rawJSON)
        case "error":
            return parseError(json, rawJSON: rawJSON)
        default:
            return parseSystemMessage(json, type: type, rawJSON: rawJSON)
        }
    }

    // MARK: - Assistant Messages

    private func parseAssistantMessage(_ json: [String: Any], rawJSON: String) -> LogEntry {
        // Flat format: top-level content string
        if let message = json["content"] as? String {
            return LogEntry(type: .assistantText, content: message, rawJSON: rawJSON)
        }

        // Flat format: top-level content array
        if let contentArray = json["content"] as? [[String: Any]] {
            let text = extractTextFromContentArray(contentArray)
            if !text.isEmpty {
                return LogEntry(type: .assistantText, content: text, rawJSON: rawJSON)
            }
        }

        // Nested format: message.content array
        if let messageDict = json["message"] as? [String: Any],
           let contentArray = messageDict["content"] as? [[String: Any]] {
            // Check for text blocks first
            let text = extractTextFromContentArray(contentArray)
            if !text.isEmpty {
                return LogEntry(type: .assistantText, content: text, rawJSON: rawJSON)
            }

            // Check for tool_use blocks (assistant messages often wrap tool_use this way)
            let toolUseBlocks = contentArray.filter { ($0["type"] as? String) == "tool_use" }
            if !toolUseBlocks.isEmpty {
                let content = toolUseBlocks.map { formatToolUseBlock($0) }.joined(separator: "\n")
                return LogEntry(type: .toolUse, content: content, rawJSON: rawJSON)
            }

            // Nested string content
            if let text = messageDict["content"] as? String {
                return LogEntry(type: .assistantText, content: text, rawJSON: rawJSON)
            }
        }

        // Flat format: top-level message string
        if let message = json["message"] as? String {
            return LogEntry(type: .assistantText, content: message, rawJSON: rawJSON)
        }

        return LogEntry(type: .assistantText, content: extractFallbackContent(from: json), rawJSON: rawJSON)
    }

    // MARK: - User Messages (tool results returned to Claude)

    private func parseUserMessage(_ json: [String: Any], rawJSON: String) -> LogEntry {
        guard let messageDict = json["message"] as? [String: Any],
              let contentArray = messageDict["content"] as? [[String: Any]] else {
            // No message.content — try top-level tool_use_result
            if let resultStr = json["tool_use_result"] as? String {
                return LogEntry(type: .toolResult, content: resultStr, rawJSON: rawJSON)
            }
            return LogEntry(type: .system, content: extractFallbackContent(from: json), rawJSON: rawJSON)
        }

        // Check what kind of blocks we have
        let toolResultBlocks = contentArray.filter { ($0["type"] as? String) == "tool_result" }
        let textBlocks = contentArray.filter { ($0["type"] as? String) == "text" }

        // tool_result blocks: extract content from each
        if !toolResultBlocks.isEmpty {
            let isError = toolResultBlocks.contains { ($0["is_error"] as? Bool) == true }
            let parts = toolResultBlocks.compactMap { extractToolResultBlockContent($0) }
            let content = parts.joined(separator: "\n")

            if !content.isEmpty {
                return LogEntry(type: isError ? .error : .toolResult, content: content, rawJSON: rawJSON)
            }

            // Fall back to top-level tool_use_result
            if let resultStr = json["tool_use_result"] as? String {
                return LogEntry(type: isError ? .error : .toolResult, content: resultStr, rawJSON: rawJSON)
            }
        }

        // text blocks: user prompt to agent (sub-conversation)
        if !textBlocks.isEmpty {
            let text = extractTextFromContentArray(textBlocks)
            if !text.isEmpty {
                return LogEntry(type: .system, content: "[agent prompt] \(text)", rawJSON: rawJSON)
            }
        }

        // Fallback to tool_use_result string if present
        if let resultStr = json["tool_use_result"] as? String {
            return LogEntry(type: .toolResult, content: resultStr, rawJSON: rawJSON)
        }

        return LogEntry(type: .toolResult, content: extractFallbackContent(from: json), rawJSON: rawJSON)
    }

    // MARK: - Tool Use (flat format)

    private func parseToolUse(_ json: [String: Any], rawJSON: String) -> LogEntry {
        // Try top-level fields first, then nested message dict
        let source: [String: Any]
        if json["tool"] != nil || json["name"] != nil || json["input"] != nil {
            source = json
        } else if let messageDict = json["message"] as? [String: Any],
                  let contentArray = messageDict["content"] as? [[String: Any]] {
            source = contentArray.first { ($0["type"] as? String) == "tool_use" } ?? json
        } else {
            source = json
        }

        return LogEntry(type: .toolUse, content: formatToolUseBlock(source), rawJSON: rawJSON)
    }

    // MARK: - Tool Result (flat format)

    private func parseToolResult(_ json: [String: Any], rawJSON: String) -> LogEntry {
        let content: String
        if let output = json["output"] as? String {
            content = output
        } else if let contentArray = json["content"] as? [[String: Any]] {
            content = extractTextFromContentArray(contentArray)
        } else if let messageDict = json["message"] as? [String: Any] {
            if let contentArray = messageDict["content"] as? [[String: Any]] {
                content = extractTextFromContentArray(contentArray)
            } else if let output = messageDict["output"] as? String {
                content = output
            } else {
                content = extractFallbackContent(from: json)
            }
        } else {
            content = extractFallbackContent(from: json)
        }
        return LogEntry(type: .toolResult, content: content, rawJSON: rawJSON)
    }

    // MARK: - Result

    private func parseResult(_ json: [String: Any], rawJSON: String) -> LogEntry {
        let content: String
        if let result = json["result"] as? String {
            content = result
        } else if let text = json["text"] as? String {
            content = text
        } else if let messageDict = json["message"] as? [String: Any] {
            if let contentArray = messageDict["content"] as? [[String: Any]] {
                content = extractTextFromContentArray(contentArray)
            } else if let result = messageDict["result"] as? String {
                content = result
            } else {
                content = extractFallbackContent(from: json)
            }
        } else {
            content = extractFallbackContent(from: json)
        }

        if content.contains("<ridler-complete/>") {
            completionSubject.send()
        }

        return LogEntry(type: .assistantText, content: content, rawJSON: rawJSON)
    }

    // MARK: - Error

    private func parseError(_ json: [String: Any], rawJSON: String) -> LogEntry {
        let content: String
        if let error = json["error"] as? [String: Any] {
            let message = error["message"] as? String ?? "Unknown error"
            let errorType = error["type"] as? String ?? ""
            content = errorType.isEmpty ? message : "[\(errorType)] \(message)"
        } else if let message = json["message"] as? String {
            content = message
        } else if let error = json["error"] as? String {
            content = error
        } else {
            content = extractFallbackContent(from: json)
        }
        return LogEntry(type: .error, content: content, rawJSON: rawJSON)
    }

    // MARK: - System Messages

    private func parseSystemMessage(_ json: [String: Any], type: String, rawJSON: String) -> LogEntry {
        // Handle system init messages with subtype
        if let subtype = json["subtype"] as? String {
            let details = formatSystemInit(json, subtype: subtype)
            return LogEntry(type: .system, content: details, rawJSON: rawJSON)
        }

        if let message = json["message"] as? String {
            return LogEntry(type: .system, content: "[\(type)] \(message)", rawJSON: rawJSON)
        }

        return LogEntry(type: .system, content: "[\(type)] \(extractFallbackContent(from: json))", rawJSON: rawJSON)
    }

    // MARK: - Helpers

    /// Format a system init message with key info extracted.
    private func formatSystemInit(_ json: [String: Any], subtype: String) -> String {
        var parts: [String] = ["[system:\(subtype)]"]
        if let model = json["model"] as? String {
            parts.append("model: \(model)")
        }
        if let cwd = json["cwd"] as? String {
            parts.append("cwd: \(cwd)")
        }
        if let version = json["claude_code_version"] as? String {
            parts.append("v\(version)")
        }
        return parts.joined(separator: " ")
    }

    /// Format a single tool_use block into human-readable text.
    private func formatToolUseBlock(_ block: [String: Any]) -> String {
        let toolName = block["tool"] as? String
            ?? block["name"] as? String
            ?? "unknown"

        var content = "Tool: \(toolName)"

        if let input = block["input"] as? [String: Any] {
            if let command = input["command"] as? String {
                content += "\n$ \(command)"
            } else if let filePath = input["file_path"] as? String {
                content += "\n\(filePath)"
            } else if let pattern = input["pattern"] as? String {
                content += "\nPattern: \(pattern)"
            } else if let prompt = input["prompt"] as? String {
                // Task/agent tool — show the prompt (truncated)
                let truncated = prompt.prefix(200)
                content += "\n\(truncated)\(prompt.count > 200 ? "..." : "")"
            }
        }

        return content
    }

    /// Extract content from a tool_result block inside a user message.
    /// The `content` field can be a string or an array of text blocks.
    private func extractToolResultBlockContent(_ block: [String: Any]) -> String? {
        // Content as a plain string
        if let contentStr = block["content"] as? String {
            // Strip tool_use_error XML tags for cleaner display
            let cleaned = contentStr
                .replacingOccurrences(of: "<tool_use_error>", with: "")
                .replacingOccurrences(of: "</tool_use_error>", with: "")
                .trimmingCharacters(in: .whitespacesAndNewlines)
            return cleaned.isEmpty ? nil : cleaned
        }

        // Content as an array of text blocks
        if let contentArray = block["content"] as? [[String: Any]] {
            let text = extractTextFromContentArray(contentArray)
            return text.isEmpty ? nil : text
        }

        return nil
    }

    /// Extract text from a content array of content blocks (e.g., `[{"type":"text","text":"..."}]`).
    private func extractTextFromContentArray(_ contentArray: [[String: Any]]) -> String {
        contentArray.compactMap { block -> String? in
            if block["type"] as? String == "text" {
                return block["text"] as? String
            }
            return nil
        }.joined(separator: "\n")
    }

    private func extractFallbackContent(from json: [String: Any]) -> String {
        if let data = try? JSONSerialization.data(withJSONObject: json, options: []),
           let text = String(data: data, encoding: .utf8) {
            return text
        }
        return "<unparseable>"
    }
}
